default: &default
  adapter: postgresql
  encoding: utf8
  pool: 50
  timeout: 5000
  username: postgres
  password:
  host: db
  port: 5432
  template: template0

development:
  <<: *default
  database: elastic_search_development

test:
  <<: *default
  database: elastic_search_test

production:
  <<: *default
  database: elastic_search_production